name: Lint Code Base
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-check
