name: Lint Code Base
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-check
